from google.adk.agents import Agent


def expense_analyzer(question: str):
    return """
SmartExpenseAI Analysis

Question:
{0}

Result:
- Expense tracking completed
- Spending categories analyzed
- Budget suggestions generated

Recommendations:
1. Track daily expenses
2. Reduce unnecessary spending
3. Create monthly saving goals

Generated by SmartExpenseAI Agent
""".format(question)


root_agent = Agent(
    name="SmartExpenseAI",
    description="Expense management AI Agent",
    instruction="""
You are SmartExpenseAI.
Help users manage and analyze expenses.
Use the expense_analyzer tool.
""",
    tools=[
        expense_analyzer
    ]
)